#ifndef ____HAL_WIFI_H_
#define ____HAL_WIFI_H_


#define ESP12_AT_LEN 70

#define WIFI_TX_QUEUE_SUM			    10		//发送网关命令队列组个数	
#define WIFI_TX_BUFFSIZE_MAX			200     //2 + 198

#define WIFI_RXBUFFSIZE_MAX		    	800


enum
{
	ESP12_AT_RESET =0,
	ESP12_AT_AT,
	ESP12_AT_ATE,	
	ESP12_AT_CWMODE,	
	ESP12_AT_CWAUTOCONN,		
	ESP12_AT_CWSTARTSMART,	
	ESP12_AT_CWSTOPSMART,	
	ESP12_AT_CWSTATE,
	ESP12_AT_CWLAP,	
	
	ESP12_AT_MQTTUSERCFG,// "AT+MQTTUSERCFG=0,1,\"", 
	ESP12_AT_MQTTCONN,// "AT+MQTTCONN=0,\"",   
	ESP12_AT_MQTTPUB,// "AT+MQTTPUB=0,\"",    
	ESP12_AT_MQTTSUB,// "AT+MQTTSUB=0,\"",     
	ESP12_AT_MQTTCLEAN,// "AT+MQTTCLEAN=0",    
	ESP12_AT_MAX,
};


typedef enum
{
	ESP12_AT_RESPONSE_WIFI_CONNECTED =0,
	ESP12_AT_RESPONSE_WIFI_DISCONNECT,
	ESP12_AT_RESPONSE_CWSTATE,	
	ESP12_AT_RESPONSE_CWJAP,
	ESP12_AT_RESPONSE_ERROR,
	ESP12_AT_RESPONSE_SMART_GET_WIFIWINFO,	
	ESP12_AT_RESPONSE_SMART_SUC,	
	ESP12_AT_RESPONSE_CWLAP,
	
	ESP12_AT_RESPONSE_MQTTCONN,			//	"+MQTTCONNECTED:0\0",
	ESP12_AT_RESPONSE_MQTTDISCONN,		//"+MQTTDISCONNECTED:0\0",
	ESP12_AT_RESPONSE_MQTTRECV,			//"+MQTTSUBRECV:0,\0",
	ESP12_AT_RESPONSE_OK,
	ESP12_AT_RESPONSE_MAX,
	
}en_esp12_atResponse;


typedef enum
{
	ESP12_STA_RESET,  				//模块重置         			AT+RST
	ESP12_STA_WIFI_POWER, 			//检测WIFI模块				AT		
	ESP12_STA_INIT,      			//WIFI模块初始化
	ESP12_STA_WIFISTA,        	//WIFI模块联网状态
	ESP12_STA_GET_PASSWORD,     	//获取WIFI密码
	ESP12_STA_GET_SMART_WIFINFO,    //获取WIFI信息 ，等待联网
	ESP12_STA_GETING_SUC,       	//配网成功
	ESP12_STA_DETEC_READY,      	//WIFI模块工作就绪
	ESP12_STA_UP_ALARMDAT,     		//上报报警信息	
}en_Esp12_sta;


typedef enum
{
	STA_WIFI_POWER_IDLE,
	STA_WIFI_POWER_RESET,
//		STA_WIFI_POWER_BREAK,
//		STA_WIFI_POWER_LINK,
		STA_WIFI_POWER_MAX,
}en_wifiPowerManageSta;

void mt_wifi_init(void);
void mt_wifi_pro(void);

#endif
